'use client'; import { useEffect,useState } from 'react';
export default function Admin(){const [password,setPassword]=useState('');const [data,setData]=useState<any>();const [error,setError]=useState('');
 async function load(){const r=await fetch('/api/admin/data');const x=await r.json();if(r.ok)setData(x)} useEffect(()=>{load()},[]);
 async function login(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok)load();else setError('Incorrect password')}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});setData(undefined)}
 if(!data)return <main className="shell section"><form className="card" onSubmit={login} style={{maxWidth:480,margin:'auto'}}><h1>Host dashboard</h1><div className="field"><label>Admin password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div>{error&&<p className="notice error">{error}</p>}<div className="actions"><button className="btn">Sign in</button><a className="btn secondary" href="/">Back</a></div></form></main>;
 const active=data.guests?.filter((g:any)=>g.status==='confirmed')||[];const total=active.reduce((s:number,g:any)=>s+g.party_size,0);
 return <main className="shell section"><div className="actions" style={{justifyContent:'space-between'}}><div><div className="eyebrow">Private host area</div><h1 style={{fontFamily:'Georgia,serif'}}>Nesting Party Dashboard</h1></div><button className="btn secondary" onClick={logout}>Log out</button></div>
 <div className="grid"><div className="card"><strong>{active.length}</strong><p className="meta">RSVPs</p></div><div className="card"><strong>{total}</strong><p className="meta">Total guests</p></div><div className="card"><strong>{data.tasks?.length||0}</strong><p className="meta">Available tasks</p></div></div>
 <section className="section"><div className="card"><h2>Guest schedule</h2><table className="admin-table"><thead><tr><th>Guest</th><th>Time</th><th>Tasks</th><th>Contact / notes</th><th>Status</th></tr></thead><tbody>{data.guests?.map((g:any)=><tr key={g.id}><td><strong>{g.name}</strong><br/>Party of {g.party_size}</td><td>{g.arrival_time}–{g.departure_time}</td><td>{g.task_signups?.map((x:any)=><span className="pill" key={x.tasks?.title}>{x.tasks?.title}</span>)||'Flexible'}</td><td>{g.email}<br/>{g.phone}<br/><span className="meta">{g.notes}</span></td><td>{g.status}</td></tr>)}</tbody></table></div></section>
 <section><div className="card"><h2>Task coverage</h2>{data.tasks?.map((t:any)=>{const n=t.task_signups?.[0]?.count||0;return <div key={t.id} style={{margin:'18px 0'}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>{t.title}</strong><span>{n}/{t.helpers_needed}</span></div><div className="progress"><span style={{width:`${Math.min(100,n/t.helpers_needed*100)}%`}}/></div></div>})}</div></section></main>}
